nameOverride: ""
fullnameOverride: ""

image:
  name: ghcr.io/stackhpc/beegfs-client
  pullPolicy: Always 
  tag: 7.1.4-5.6.14-300.fc32.x86_64

nodeSelector:
  magnum.openstack.org/role: worker

priorityClassName: system-node-critical

tolerations:
- effect: NoExecute
  operator: Exists
- effect: NoSchedule
  operator: Exists

clients:
- name: storage-nvme
  address: 10.60.253.20
  port: 28004
  hostPath: /mnt/storage-nvme
- name: storage-ssd
  address: 10.60.253.50
  port: 58004
  hostPath: /mnt/storage-ssd

buildArgs: -j8 # BEEGFS_OPENTK_IBVERBS=1
