apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: beegfs
  name: beegfs-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: beegfs
  template:
    metadata:
      labels:
        name: beegfs
    spec:
      nodeSelector:
        magnum.openstack.org/nodegroup: old
      containers:
      - image: ghcr.io/stackhpc/beegfs-client:7.1.4-5.6.14-300.fc32.x86_64
        imagePullPolicy: Always
        name: helperd
        command: ["/helperd.sh"]
        securityContext:
          privileged: true
      - image: ghcr.io/stackhpc/beegfs-client:7.1.4-5.6.14-300.fc32.x86_64
        imagePullPolicy: Always
        command: ["/client.sh"]
        name: storage-nvme
        env:
        - name: BEEGFS_CLIENT_NAME
          value: storage-nvme
        - name: BEEGFS_CLIENT_IP
          value: 10.60.253.20
        - name: BEEGFS_CLIENT_PORT
          value: 28004
        - name: BEEGFS_BUILD_ARGS
          value: -j8
        volumeMounts:
        - mountPath: /mnt/beegfs
          name: storage-nvme
          mountPropagation: Bidirectional
        securityContext:
          privileged: true
      - image: ghcr.io/stackhpc/beegfs-client:7.1.4-5.6.14-300.fc32.x86_64
        imagePullPolicy: Always
        command: ["/client.sh"]
        name: storage-ssd
        env:
        - name: BEEGFS_CLIENT_NAME
          value: storage-ssd
        - name: BEEGFS_CLIENT_IP
          value: 10.60.253.50
        - name: BEEGFS_CLIENT_PORT
          value: 58004
        - name: BEEGFS_BUILD_ARGS
          value: -j8
        volumeMounts:
        - mountPath: /mnt/beegfs
          name: storage-ssd
          mountPropagation: Bidirectional
        securityContext:
          privileged: true
      hostNetwork: true
      volumes:
      - name: storage-nvme
        hostPath:
          path: /mnt/storage-nvme
      - name: storage-ssd
        hostPath:
          path: /mnt/storage-ssd
