apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: beegfs-ds
    tier: monitor
  name: beegfs-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: beegfs-ds
  template:
    metadata:
      labels:
        name: beegfs-ds
      name: beegfs-pod
    spec:
      containers:
      - image: docker.io/brtknr/beegfs-client:7_1-4.19.3-300.fc29.x86_64
        imagePullPolicy: Always
        name: beegfs-test
        env:
        - name: BEEGFS_MGMTD_HOST
          value: 10.60.253.20
        volumeMounts:
        - mountPath: /mnt/beegfs
          name: beegfs-vol
          mountPropagation: Bidirectional
        securityContext:
          privileged: true
      hostNetwork: true
      volumes:
      - name: beegfs-vol
        hostPath:
          path: /mnt/storage-nvme
